-- プロフィール拡張・学習記録の場所区分
ALTER TABLE students ADD COLUMN IF NOT EXISTS last_name VARCHAR(50);
ALTER TABLE students ADD COLUMN IF NOT EXISTS first_name VARCHAR(50);
ALTER TABLE students ADD COLUMN IF NOT EXISTS phone VARCHAR(30);
ALTER TABLE students ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE students ADD COLUMN IF NOT EXISTS birth_date DATE;
ALTER TABLE students ADD COLUMN IF NOT EXISTS school_name VARCHAR(200);

ALTER TABLE daily_study_records ADD COLUMN IF NOT EXISTS study_location VARCHAR(20) NOT NULL DEFAULT 'school';
